instance:
  no_inits: 1
  seed_value: 0
  lr: 0.001
  min_delta: 1e-2
  patience: 3
  verbose: 2
  dropout: 0.2
  n_process: 2
  model_selection: 'IC'
  n_splits: 5
  cv_approach: 'trend' # 'full' or 'trend' or 'simple'
  formulation : 'regional'          # Model formulation, "global" or "regional"
  timeout_per_node: 1000
  n_countries: 196
  time_periods: 63
  dynamic_model: True
  holdout: 0
  within_transform: False
  add_fe: True
  data_source: 'ee'   #ee or worldbank
  nodes_list:
    - (2,)
    # - (4,)
    # - (8,)
    # - (16,)
    # - (32,)
    # - (48,)
    # - (64,)
    # - (2,2,)
    # - (4,2,)
    # - (4,4,)
    # - (8,2,)
    # - (8,4,)
    # - (8,8,)
    # - (16,2,)
    # - (16,4,)
    # - (16,8,)
    # - (16,16,)
    # - (32,2,)
    # - (32,4,)
    # - (32,8,)
    # - (32,16,)
    # - (32,32,)
    # - (2,2,2,)
    # - (4,2,2,)
    # - (4,4,2,)
    # - (4,4,4,)
    # - (8,2,2,)
    # - (8,4,4,)
    # - (8,8,2,)
    # - (8,8,4,)
    # - (8,8,8,)
    # - (16,2,2,)
    # - (16,4,2,)
    # - (16,4,4,)
    # - (16,8,2,)
    # - (16,8,4,)
    # - (16,8,8,)
    # - (16,16,2,)
    # - (16,16,4,)
    # - (16,16,8,)
    # - (16,16,16,)
    # - (32,2,2,)
    # - (32,4,2,)
    # - (32,4,4,)
    # - (32,8,2,)
    # - (32,8,4,)
    # - (32,8,8,)
    # - (32,16,2,)
    # - (32,16,4,)
    # - (32,16,8,)
    # - (32,16,16,)
    # - (32,32,2,)
    # - (32,32,4,)
    # - (32,32,8,)
    # - (32,32,16,)
    # - (32,32,32,)
